name: DevRelease

on:
  push:
    branches:
      - "main"
      - "github/workflow"
jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'release:')"
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
          submodules: true
          lfs: true
    - name: Update version.
      run: |
        current_version=$(grep '__version__ = ' src/cracknuts_squirrel/__init__.py | awk -F'"' '{print $2}')
        if [ -z "$current_version" ]; then
            echo "Error: Could not extract __version__ from __init__.py"
            exit 1
        fi
        commit_sha=$(git rev-parse --short HEAD)
        dev_version="${current_version}+g${commit_sha}"
        sed -i "s/__version__ = \".*\"/__version__ = \"$dev_version\"/" src/cracknuts_squirrel/__init__.py
        echo Update version to: $dev_version
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install build
        pip install twine
    - name: Build the project
      run: |
        python -m build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cracknuts-dist-${{ github.sha }}
        path: dist/
        retention-days: 7
