name: DevRelease

on:
  push:
    branches:
      - "main"
      - "github/workflow"
jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'release:')"
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          # get tag history for version number
          fetch-depth: 0
          submodules: true
    - name: Update version.
      run: |
        incremented_version=`grep '__version__ = ' src/cracknuts_squirrel/__init__.py | awk -F'"' '{print $2}' | awk -F'-' '
        {
            if (NF == 1) {
                # 非 alpha 版本，例如 1.0.0
                split($1, ver, ".")
                printf "%d.%d.%d\n", ver[1], ver[2], ver[3] + 1
            } else if (NF == 2) {
                # alpha 版本，例如 1.0.0-alpha.1
                split($1, ver, ".")
                split($2, alpha, ".")
                printf "%d.%d.%d-alpha.%d\n", ver[1], ver[2], ver[3], alpha[2] + 1
            }
        }'`
        n_commits=`git rev-list $(git describe --tags --abbrev=0)..HEAD --count`
        if [ "$n_commits" -eq 0 ]; then
          echo "No new commits since the last tag. Terminating the action."
          exit 0
        fi
        dev_version="${incremented_version}.dev${n_commits}"
        sed -i "s/__version__ = \".*\"/__version__ = \"$dev_version\"/" src/cracknuts_squirrel/__init__.py
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install node dependencies
      run: |
        cd jupyter_frontend
        npx pnpm install
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install build
        pip install twine
    - name: Build jupyter frontend
      run: |
        cd jupyter_frontend
        npm run clean-build
    - name: Build the project
      run: |
        python -m build
    - name: Upload to test pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.TESTPYPI_TOKEN}}
      run: |
        python -m twine upload --repository testpypi dist/* --non-interactive
