name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta*'
      - '[0-9]+.[0-9]+.[0-9]+-rc*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compare tag name with version string.
        run: |
          # Get the triggered tag name
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          # Extract version from __init__.py
          VERSION=$(grep -oP "(?<=__version__ = \")[^\"]+" src/cracknuts_squirrel/__init__.py)
          # Compare tag name with version
          if [[ "$TAG_NAME" != "$VERSION" ]]; then
            echo "Error: Tag name '$TAG_NAME' does not match the version '$VERSION' in __init__.py"
            exit 1
          else
            echo "Tag name '$TAG_NAME' matches the version '$VERSION'."
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install jupyter frontend dependencies
        run: |
          cd jupyter_frontend
          npx pnpm install
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build tools
        run: |
          pip install build
      - name: Build jupyter frontend
        run: |
          cd jupyter_frontend
          npm run clean-build
      - name: Build the package
        run: |
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/*

  upload-to-github-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload-to-pypi:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install twine
        run: |
          pip install twine
      - name: Upload to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
        run: |
          python -m twine upload dist/* --non-interactive
